# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=150)),
                ('type_of_defect', models.CharField(max_length=150)),
                ('column', models.IntegerField()),
                ('line', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DefectSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('repository', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='defect',
            name='defect_search',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firstwin.DefectSearch'),
        ),
    ]
