# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 17:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstwin', '0002_auto_20170326_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectsearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
