# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstwin', '0003_auto_20170326_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectsearch',
            name='defects_amount',
            field=models.IntegerField(default=0),
        ),
    ]
